Repository ASFHyP3/mkdocs-asf-theme, pull requests merged in 2021-01, with the labels that each got.

#19 fix missing in footer
  asf_theme/partials/footer.html
Labels: bumpless

#22 Handle pip package name being different than the python package name
  asf_theme/__init__.py
Labels: bug, bumpless

#20 RELEASE 0.2.1 fix call to document.clear()
  .github/pull_request_template.md
  .github/workflows/tag-and-distribute.yml
  CHANGELOG.md
  README.md
  asf_theme/__init__.py
  asf_theme/partials/footer.html
  setup.py
Labels: patch
